/**
 * Generates the SQL files loaded into D1 (run from the repository root: `npm run build-sql`).
 *
 *   sql/schema.sql             tables + FTS5 virtual table + q_cache (hand-written, checked in)
 *   sql/load-propositions.sql  chapters, sections, 868 units (837 propositions + 31 intro/part paragraphs)
 *   sql/load-fts.sql           the same units into the FTS5 table (text with digit groups merged)
 *   src/stopwords.generated.ts the stopword list of eval/retrieval-core.ts, for the Worker
 *
 * Units are built by `buildProjection()` of eval/retrieval-core.ts, so rows, prefixes and merged
 * measure_split paragraphs are exactly those of variant A (eval/retrieval-results.json).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  STOPWORDS,
  buildProjection,
  loadInputs,
  processTerm as processTermA,
  tokenize as tokenizeA,
} from '../../../../eval/retrieval-core.ts';

const labDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const ROWS_PER_INSERT = 40;

function sqlString(value: string | null): string {
  return value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`;
}

function insertBatches(
  table: string,
  columns: readonly string[],
  rows: readonly (string | null)[][],
): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += ROWS_PER_INSERT) {
    const values = rows
      .slice(i, i + ROWS_PER_INSERT)
      .map((r) => `(${r.map(sqlString).join(', ')})`)
      .join(',\n');
    out.push(`INSERT INTO ${table} (${columns.join(', ')}) VALUES\n${values};`);
  }
  return `${out.join('\n')}\n`;
}

// 1. Stopwords for the Worker (kept in sync with variant A by generation, not by hand).
const stopwordsFile = join(labDir, 'src', 'stopwords.generated.ts');
writeFileSync(
  stopwordsFile,
  `// Generated by scripts/build-sql.ts from eval/retrieval-core.ts STOPWORDS — do not edit.\nexport const STOPWORDS: ReadonlySet<string> = new Set(${JSON.stringify([...STOPWORDS].sort())});\n`,
);

// 2. Drift check: the Worker pipeline must tokenize like variant A.
const { mergeDigitGroups, processTerm, tokenize } = await import('../src/query.ts');
const inputs = loadInputs();
const projection = buildProjection(inputs.dataset);
let checked = 0;
for (const unit of projection.units) {
  const sample = `${unit.prefix} ${unit.text}`;
  const a = tokenizeA(sample).map(processTermA);
  const b = tokenize(sample).map(processTerm);
  if (JSON.stringify(a) !== JSON.stringify(b)) {
    throw new Error(`query.ts drifted from eval/retrieval-core.ts on unit ${unit.id}`);
  }
  checked += a.length;
}
for (const q of inputs.questionsFile.questions) {
  const a = tokenizeA(q.question).map(processTermA);
  const b = tokenize(q.question).map(processTerm);
  if (JSON.stringify(a) !== JSON.stringify(b)) throw new Error(`drift on question ${q.id}`);
}

// 3. Data files.
const chapters = inputs.dataset.chapters.map((c) => [c.id, c.partId, String(c.number), c.title]);
const sections = inputs.dataset.sections.map((s) => [s.id, s.chapterId, String(s.number), s.title]);
const units = projection.units.map((u) => [
  u.id,
  u.sectionId,
  u.chapterId,
  u.kind,
  u.text,
  u.prefix,
]);

const loadPropositions =
  `-- Generated by scripts/build-sql.ts from data/aec-2025.json (corpus ${inputs.dataset.meta.corpus_version}).\n` +
  `-- Text: La France insoumise – L'Avenir en commun, CC BY-NC-SA 4.0.\n` +
  insertBatches('chapters', ['id', 'part_id', 'number', 'title'], chapters) +
  insertBatches('sections', ['id', 'chapter_id', 'number', 'title'], sections) +
  insertBatches(
    'propositions',
    ['id', 'section_id', 'chapter_id', 'kind', 'text', 'prefix'],
    units,
  );

// FTS copy: digit groups merged so "10 000" is one token on both sides (unicode61 splits on spaces).
const ftsRows = projection.units.map((u) => [
  mergeDigitGroups(u.text),
  mergeDigitGroups(u.prefix),
  u.id,
  u.sectionId,
  u.chapterId,
]);
const loadFts =
  `-- Generated by scripts/build-sql.ts (corpus ${inputs.dataset.meta.corpus_version}). FTS5 copy of the units.\n` +
  insertBatches('propositions_fts', ['text', 'prefix', 'id', 'section_id', 'chapter_id'], ftsRows);

mkdirSync(join(labDir, 'sql'), { recursive: true });
writeFileSync(join(labDir, 'sql', 'load-propositions.sql'), loadPropositions);
writeFileSync(join(labDir, 'sql', 'load-fts.sql'), loadFts);

const kinds = new Map<string, number>();
for (const u of projection.units) kinds.set(u.kind, (kinds.get(u.kind) ?? 0) + 1);
console.log(
  JSON.stringify(
    {
      corpus_version: inputs.dataset.meta.corpus_version,
      chapters: chapters.length,
      sections: sections.length,
      units: units.length,
      units_by_kind: Object.fromEntries(kinds),
      stopwords: STOPWORDS.size,
      tokens_checked_for_drift: checked,
      bytes: {
        'load-propositions.sql': Buffer.byteLength(loadPropositions),
        'load-fts.sql': Buffer.byteLength(loadFts),
      },
    },
    null,
    2,
  ),
);
